# Generated by Django 4.0.3 on 2022-03-21 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

